Create pt-br.json
arcanistzed/pdf-sheet pull request #74
Opened 2023-03-22 19:13 UTC by IgorAK25

2023-08-22 12:25 UTC, gioppoluca requested changes
Can you remove the final comma?

2023-08-22 12:25 UTC, gioppoluca commented on languages/pt-br.json
> +      },
please remove comma

2023-08-27 04:23 UTC, dyoung418 commented
This should probably include a change to module.js to include the pt-br language in the manifest.

2023-09-22 11:14 UTC, gioppoluca approved these changes

2023-09-22 11:16 UTC, merged