Fixes pf2e mapping and adds pf2e-extended with full feature descriptions
arcanistzed/pdf-sheet pull request #80
Opened 2023-05-05 04:44 UTC by dyoung418

This pull requests fixes the pf2e mapping and resolves issue #77.  It is more comprehensive than pull request #78 because it also refactors all of the mapping for the new Document structure of foundryvtt.  It includes the following changes:

1. Fixes for patherfinder2e.mapping, which now runs with no console warnings at all
2. A single fix for pdfsheet.js to replace all '@'s in mappings with 'actor.' instead of 'actor.data.' to comply with the new document model.  I have tested this with the dnd5e mapping (unchanged) and it works fine.  This change in pdfsheet.js is required in order for the new pathfinder2e.mapping in this pull request to work.
3. Adds a new mapping: pathfinder2e-extended-descriptions.mapping which can be used with a different pathfinder2e PDF file to add pages with full descriptions of all features and spells.  I added the download link for the alternate PDF that this mapping uses to the README.md file in mappings/ and also included the link at the top of the .mapping file.  However, the download button in the settings page can only have one PDF per game.system value, so there isn't a way to add the PDF to that download button.

2023-08-22 12:18 UTC, gioppoluca submitted a review, later dismissed

2023-08-22 12:21 UTC, gioppoluca requested changes
Can you please recheck Dnd5.mapping there was a previous PR that did some changes.
Once you do I'll be able to review it and we'll publish it

2023-08-22 21:10 UTC, dyoung418 commented
> Can you please recheck Dnd5.mapping there was a previous PR that did some changes. Once you do I'll be able to review it and we'll publish it

I have merged in the commited changes so the conflict in dnd5.mapping is no longer present.

2023-08-22 21:12 UTC, dyoung418 commented
Sorry, I didn't mean to close the pull request.  Reopening now and we should have a clean PR now.

2023-08-23 06:50 UTC, gioppoluca approved these changes

2023-08-23 07:07 UTC, merged